#!/bin/bash
[ ! -f "${1}" ] && exit 1
FILENAME=$(basename ${1} | sed 's/.img$//')
DIRNAME=$(dirname $(realpath ${1}))
./bbbuilder mount ${1}
sudo umount /tmp/bbbuild/root/var/cache/apt/archives /tmp/bbbuild/root/mnt/resources /tmp/bbbuild/root/proc /tmp/bbbuild/root/dev/pts /tmp/bbbuild/root/run
cd /tmp/bbbuild/root/
sudo tar --exclude=./tmp -cf ${DIRNAME}/${FILENAME}.tar .
cd -
./bbbuilder unmount
sudo xz -T0 ${DIRNAME}/${FILENAME}.tar
sudo chown $(id -u):$(id -g) ${DIRNAME}/${FILENAME}.tar.xz
aws s3api put-object --bucket bbb-build-artifacts --key moode/${FILENAME}.tar.xz --body ${DIRNAME}/${FILENAME}.tar.xz --storage-class ONEZONE_IA &&
rm -f ${DIRNAME}/${FILENAME}.tar.xz &&
rm -f ${1}
