#!/bin/bash
[ ! -f "${1}" ] && exit 1
FILENAME=$(basename ${1} | sed 's/.img$//')
DIRNAME=$(dirname $(realpath ${1}))
aws s3api put-object --bucket bbb-build-artifacts --key moode/${FILENAME}.tar.xz --body ${DIRNAME}/${FILENAME}.tar.xz --storage-class ONEZONE_IA &&
rm -f ${DIRNAME}/${FILENAME}.tar.xz &&
rm -f ${1}
